### ISSUE TITLE
Add express as peer dependency?

### ISSUE THREAD

**Issue by skleeschulte** [tkoenig89/express-static-gzip#10]
It might be better to add express as a peer dependency, so it is always used the static middleware of the app's express installation.

**Comment by tkoenig89** [comment]
Hey,

not sure i understood your point corretly, but express is already declared as a 'main' dependency in package.json. This should already ensure that express-static-gzip, is always used with express.

**Comment by skleeschulte** [comment]
What I meant is to add express as a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) *instead* of adding it as a regular dependency. But then, after looking at the code of express-static-gzip and express, I see that it probably does not matter.

The long story is: I was under the impression that express should be used with the express.static middleware that is bundled with the express version in use. Say I would install `express@4.13` and the latest `express-static-gzip`. Now npm would install a separate copy of express for express-static-gzip (currently 4.15.3) to meet its express dependency of ^4.14.0. If express would be set as peerDependency, npm would instead warn that express-static-gzip's peer dependency is not met. But since express itself really only exposes [`serve-static`](https://www.npmjs.com/package/serve-static) under `express.static`, and there does not seem to be any "tight" coupling between express and serve-static, it probably does not matter.

Another possibility would be to require `serve-static` directly instead of `express.static`.

**Comment by tkoenig89** [comment]
I must admit, I did not fully understood the peer dependency thing :). Maybe I should read some more about it.

But I defenitly liked your point on using `serve-static` directly instead of the indirection through express. This is what i changed so far.

If this solves your point, I guess we can close this issue?!
