### ISSUE TITLE
When using defualt gzip, there is no Content-Encoding header

### ISSUE THREAD

**Issue by Igor-Vuk** [tkoenig89/express-static-gzip#12]
I compress files beforehand with webpack, so I have for example bundle.js, bundle.js.gz and bundle.js.br If I leave everything default and just use gzip when I inspect response headers in browser I see no Content-Encoding. There is also no indication of size difference which is interesting because if I inspect with curl I see Content-Encoding: gzip and also some online tests are reporting that I am using gzip. 

If I turn on option for brotli, everything is working as it should. If I inspect response Headery in browser I see Content-Encoding and I also see the size difference, the size of original file and the size of brotli zip version.

So I am not sure in the end if gzip is enabled.

**Comment by tkoenig89** [comment]
Hi,

i just checked with the latest version (0.2.3) and everything seems fine. One thing I found, that might explain your observations, is browser caching and / or the use of ETags by the server-static middleware. 

So when i first request a gziped file, chrome gets a 200 response and the file is served with Content-Encoding: gzip and in a very small size. Second time i request the same file, chrome shows a 304 (Not Modified) response, that does not have any Content-Encoding and is quite large.

So for me this looks like browser is caching the file, which makes it look like it does not use gzip compression. In chrome's  network tab you can disable caching, which then should lead to every request being served as Content-Encoding: gzip.

Hope this helps.

**Comment by Igor-Vuk** [comment]
Hi tkoenig89,
thanks for looking into it. I tried by disabling cache already, It didn't help. It is pretty weird. Online testing tools show that I am using gzip, curl shows also but there is no indication in browser for gzip, just brotli. I also noticed that it doesnt serve index.html.gz but it is not in dist(asset folder) so I guess I shouldn't even count on that. You can observe the behaviour here. Server folder is in src/server/prodServer, just run **yarn run start-run** after **yarn install** or **npm instal** and listen on localhost:3001
https://github.com/Igor-Vuk/TimerApp/tree/nginx

**Comment by tkoenig89** [comment]
Hi Igor,

sorry that it took me a while to get back to you. Had a busy week.

I checked out your project and tried to get it running. Did not work. Seems like there are some issues, while building the application. Some image could not be resolved. I stoped at that point.

But I did have another look at the code of express-static-gzip, but did not find a reason why enabling brotli should fix gzip not working. And why it may not be working without brotli. 
Maybe you need to create a smaller example which allows reproducing your issue, without the big setup of your project. If you can provide such a simple example I will be happy to have another look at this issue again. But for now please understand, that I don't have the time at the moment to dig into your application in great detail.

Kind regards,
Tobi

**Comment by tkoenig89** [comment]
I did some testing alongside my latest refactoring activities and did not find any issues with serving gzip, regardless of brotli activated or not.

For now i close this issue due to inactivity and not being reproducible. 

Please feel free to reopen if there is any new evidence of this issue.
