### ISSUE TITLE
IndexFromEmptyFile is a dangerous option

### ISSUE THREAD

**Issue by MartinLoeper** [tkoenig89/express-static-gzip#17]
I just started to use this nice library and integrated it into our nodejs backend which is intended to serve both - static and dynamic content.

There is one behaviour which I did not expect: API requests to our REST endpoint stopped working if their path was ending with "/".

The issue is, that indexFromEmptyFile is enabled by default and thus every request is manipulated if it is ending with "/". - **Even** if the serve-static middleware does not handle the request.  
In our scenario, the next middleware - nestjs - cannot handle the request anymore as the path does not match.

**Comment by tkoenig89** [comment]
The reason this is enabled by default is, that you might have this serving a website staticly. You might not want the users to type the "index.html" at the end of your website's url. Which seemed to me like the most common case at the time. For all other cases it can be switched off.

Back to your issue: 
I guess you might have a setup where static files might lie somewhere in "/\*\*/\*" and your dynamic request are served from "/api/\*\*/\*". In this case the simplest solution and the one i always use in this case is to put the static fileserver at the end of the url routing. This way your API endoints ending with "/" will not be effected by _express-static-gzip_.

Should be something like this:
````Javascript
let app = express();
app.use("/api", nestjsInstance);
//...
app.use("/", expressStaticGzip("static/content"));
````

If this does not solve your issue, you might want to just disable _indexFromEmptyFile_. If there are more voices to say, it should be turned off by default, this can be done in a future version.

**Comment by MartinLoeper** [comment]
Thank you for the detailed answer!  
I already chose the option to disable *indexFromEmptyFile* which you mentioned because this is in fact easily done. It solves my issue.

However, I just wanted to make others know the issue which I encountered in case they have a similar setup. Maybe you could just add a warning somewhere in the first paragraph in the README, that expressStaticGzip does not **only extend** serveStatic by adding gzip compression (as I exprected), but  **might also cause regression** if the api requests are not handled in a middleware on top (as your snippet above illustrates).

I think, the module would be even better if a developer could easily replace serveStatic calls with expressStaticGzip calls without breaking functionality :)

All in all, thank you for the fast and concise answer!

**Comment by tkoenig89** [comment]
Just did some modifications on the readme and made it more prominent what can happen with this option. Maybe this helps others :)
