### ISSUE TITLE
Isomorphic Server Side

### ISSUE THREAD

**Issue by paulo101977** [tkoenig89/express-static-gzip#19]
There are a error at server side render (Isomorphic react render). The plugin are serving the .gz at server side. Otherwise, that file should be a .js, without the .gz extension.

**Comment by tkoenig89** [comment]
Sorry, but I don't realy get your context. Maybe you can describe your case a little more verbose. An example would be best.

But in general if  you don't want this middleware to provide compressed files, this sounds like an issue with order of registering the middlewares / endpoints.

**Comment by paulo101977** [comment]
I run other script and this work aproperty. I have make my custom gzip compression by node express config (created a custom route and file selection and set the header inside the promise method).

**Comment by tkoenig89** [comment]
Again, sorry, but I really can't help without the complete (or any) context. At least i need some code to grasp whats going on in your application and what might cause the issue. 

Also feel free to provide a pull request if you figured out the issue, and it's within _serve-gzip_.

**Comment by tkoenig89** [comment]
Closed due to inactivty
