### ISSUE TITLE
Rename "indexFromEmptyFile" to "index"

### ISSUE THREAD

**Issue by ishitatsuyuki** [tkoenig89/express-static-gzip#20]
It's how it's called in [`serve-static`](https://github.com/expressjs/serve-static#index). Renaming it allows easier migration from serve-static.

**Comment by tkoenig89** [comment]
Good point. Thanks for pointing this out.

I guess i will add the "index" option and leave the other one for now, to prevent breaking the module for others.

**Comment by tkoenig89** [comment]
Update: my latest [commit](https://github.com/tkoenig89/express-static-gzip/commit/dc96b8f2583e97a963e666d9c38118a0c02a3931) adds the `index` option. It will be part of the next release.

**Comment by tkoenig89** [comment]
This feature is now part of version `1.0.0` which has just been released to [npm](https://www.npmjs.com/package/express-static-gzip).

**Comment by tkoenig89** [comment]
Closed, as this has been released a while ago.
