### ISSUE TITLE
single-page router rendering

### ISSUE THREAD

**Issue by gregmillz** [tkoenig89/express-static-gzip#21]
I've followed your guide (using Brotli) and I'm able to render my root route '/' and nested routes as well, but of course refreshing breaks the implementation you've provided due to my client-side routing. Is there any other options to use which supports this issue? I realise I'd usually send back the index.html file on any 404 error, however I'm not sure how to accomplish this since your code snippet (if I understand correctly) handles GET requests, but I don't see an example for nested routes there. 

Any info is appreciated!

**Comment by tkoenig89** [comment]
Like you described, using client-side routing (e.g. in an Angular application) will in most cases require you to come up with a specific implementation of a backend serving index.html in most cases. 

You can try something like in [this stackoverflow answer](https://stackoverflow.com/a/20405454):

```JavaScript
// serve index.html for all remaining routes, in order to leave routing up to angular
app.all("/*", function(req, res, next) {
    res.sendfile("index.html", { root: __dirname + "/app" });
});
```
In this case you would not send the index.html file compressed, but all your other files.

A different approach would be to write a middlware that changes the requested url path before farwarding the request into your *express-static-gzip* middleware. But this might be more complicated.

**Comment by gregmillz** [comment]
Apologies for the late reply. It was an error on my part, after making your suggested change the client-side routing was fixed!
