### ISSUE TITLE
findAllCompressionFiles errors out if unable to access folder

### ISSUE THREAD

**Issue by Wizarth** [tkoenig89/express-static-gzip#29]
If a subdirectory of the directory being scanned has permissions preventing content from being read from there, findAllCompressionFiles will fail.

It looks plausible to just wrap this in a try-catch block and return on error.

```
EACCES: permission denied, scandir '[redacted]/client/wip/.cache'
    at Object.fs.readdirSync (fs.js:904:18)
    at findAllCompressionFiles ([redacted]/node_modules/express-static-gzip/index.js:132:24)
    at findAllCompressionFiles ([redacted]/node_modules/express-static-gzip/index.js:139:17)
    at expressStaticGzip ([redacted]/node_modules/express-static-gzip/index.js:30:9)

```

**Comment by tkoenig89** [comment]
As this would be an issue I would wan't to get to my attention to right away when starting the server, the current behaviour seems to me like the one I expect. 
This gives you all the details you need to identify an issue with permissions. Wrapping this in error (which i would then throw as well) would not add any benefit in my opinion. 

Is there something i don't get? What kind of information would you add to this error, after catching the above exception?

**Comment by Wizarth** [comment]
Ah, I don't consider this situation an error, in that these protected folders are intended to be there and to not be available via the web service.
That said, what I'm doing is pretty odd and if you consider the current behaviour correct, I don't have a counter-argument.

**Comment by tkoenig89** [comment]
Okay, so I guess I understand. You might just log e.g. a warning for folder that can not be parsed and keep starting the server.

At the moment I guess the common use case would be to get informed more verbosely, when a folder could not be parsed (exception), but if there are more people who see and require such a 'warn and keep going' behavior I would consider adding this in the future.

**Comment by tkoenig89** [comment]
Closed due to inactivity
