### ISSUE TITLE
Can't serve gzip files

### ISSUE THREAD

**Issue by ghost** [tkoenig89/express-static-gzip#33]
The middleware is not serving gzip files as intended.I tried reloading the server but still not working. Here's my code:

server/config/express.js
```
var path = require('path');
var express = require("express");
var expressStaticGzip = require("express-static-gzip");
var app = express();

module.exports= function() {
    app.use(express.static('./public'));
    app.use("/", expressStaticGzip(path.resolve(__dirname, '../../public/app/assets/js/')));

module.app = app;

return module;

}
```

public/app/assets/js/
- common.min.js 500KiB
- common.min.js.gz 180 KiB

When I try from the browser to access example.com/app/assets/js/common.min.js the uncompressed file is served always.

I'm using node v12.10.0, expressjs 4.17.1 and express-static-gzip 2.0.5

**Comment by tkoenig89** [comment]
Hey, writing from my cellphone i don't have the possiblity to fully check
out the details of your code.

But to me it seems like you should try to either switch the order of your
app.use statements or try to comment out the line with express.static.

I guess the first app.use is where your uncompressed file are getting
served, right? If yes, this might shadow the compressed endpoint and never
call it. Reversing the order should result in fallback to uncompressed
files, when there is no compressed version found by express-static-gzip.

Let me know if this helped.

unexpectedShr3k <notifications@github.com> schrieb am Sa., 7. Dez. 2019,
13:39:

**Comment by ghost** [comment]
I tried reversing the order and commenting out the express.static line and restarting the server but the problem still persists.

**Comment by ghost** [comment]
If I comment the static line the file is unable to be served, neither compressed or uncompressed.

**Comment by tkoenig89** [comment]
The only thing i could think of right now would be, that the path to the
files might be wrong.

Do you have compressed files next to the originals? I wonder why you
provide different paths to express.static and static-gzip.

Maybe try a more simple setup, where you copy all files (original +
compressed) into a test folder and point static-gzip to this folder. There
is no need for express.static, as static-gzip falls back to serving the
originals by itself.

Sorry that i could not be of more help at the moment.

unexpectedShr3k <notifications@github.com> schrieb am Sa., 7. Dez. 2019,
14:09:

**Comment by tkoenig89** [comment]
I just saw something else that might cause this behaviour. Totaly
overlooked this.
You provide express-static the full path to your assets/js folder. Which
results in express-static to start serving from this path as an entry
point. So all paths are relative to the assets/js folder. So you should
find the compressed common.js under example.com/common.js.

You might want to try:
app.use("/public/app/assets/js", expressStaticGzip(path.resolve(__dirname,
'../../public/app/assets/js/');

This might not be the exact solution, but you definitly want to look into
this direction.

Tobias König <tobiaskoenig1@googlemail.com> schrieb am Sa., 7. Dez. 2019,
14:41:

**Comment by ghost** [comment]
This did the trick thanks :D
```

app.use("/app/assets/js", expressStaticGzip(path.resolve(__dirname, '../../public/app/assets/js/')));
app.use(express.static('./public'));
```
