### ISSUE TITLE
Compressed files from nested folders not served

### ISSUE THREAD

**Issue by BohdanOther** [tkoenig89/express-static-gzip#34]
Hello, compressed files are served only from root directory.

I guess problem is in line 95
https://github.com/tkoenig89/express-static-gzip/blob/94767f79e861a3901e8ebba31b084abc4986817f/index.js#L87-L100

Should be   
```
    findCompressedFilesInDirectory(filePath);
```
instead of
``` 
    findCompressedFilesInDirectory(fs, filePath);
```

**Comment by tkoenig89** [comment]
Thanks for pointing this out. Removing the superfluous `fs` in the function call solves the issue.

Please checkout the new bugfix release **`2.0.6`** from npm.
