### ISSUE TITLE
express static gzip doesnt work in vue ssr

### ISSUE THREAD

**Issue by jacquesmatthieu** [tkoenig89/express-static-gzip#36]
Hi, I'm using express-static-gzip in vue ssr (no nuxt.js) and it doesn't work and I dont know why. 
I can't see content-enconding in my header

My code
```
import path from 'path';
import express from 'express';
import fs from 'fs';
import expressStaticGzip from 'express-static-gzip';

import vueServerRenderer from 'vue-server-renderer';
import dotenv from 'dotenv';
import { getTemplateFromRequest } from './template.mjs';
import serverBundle from '../dist-etu-ssr/vue-ssr-server-bundle.json';
import clientManifest from '../dist-etu-ssr/vue-ssr-client-manifest.json';
import { startApiRoutes } from './router/index.mjs';
import { preloadServer } from '../utils/server.mjs';
import redirects from './redirects/redirects.json';

const { createBundleRenderer } = vueServerRenderer;
const __dirname = path.dirname(new URL(import.meta.url).pathname);

dotenv.config();
preloadServer();
const server = express();

server.use('/dist-etu-ssr', expressStaticGzip('../dist-etu-ssr', {
    enableBrotli: true,
    orderPreference: ['br', 'gz']
}));
server.use(express.json());

startApiRoutes(server);

server.get('*', (req, res) => {
    redirects.forEach((element) => {
        if (element.pattern !== 'undefined') {
            const params = req.url.match(element.pattern);

            if (params === null) {
                return;
            }

            let redirectUrl = element.to;

            element.to.match(/([1-9])/g).forEach((number) => {
                redirectUrl = redirectUrl.replace(number, params[number]);
            });

            if (redirectUrl !== 'undefined') {
                res.redirect(redirectUrl);
            }
        }
    });
etc ...
```
My server conf is based from 
https://github.com/horprogs/vue-ssr-hmr/blob/master/app/server.js

**Comment by tkoenig89** [comment]
Beside that I do not have any experience with vue or vue ssr, your setup seems okay in regards to `express-static-gzip`.

What kind of files are inside your '../dist-etu-ssr' directory? `express-static-gzip`, does require you to provide pre-compressed files next to the js, css, etc. files. It does not compress files by itself. This might be the reason you don't see any 'content-encoding' header.

**Comment by jacquesmatthieu** [comment]
Hi, I've alreay gzip & brolti files which are build with webpack 4

**Comment by tkoenig89** [comment]
I guess (as there are no issues like this reported in the past), that this is an issue with your specific setup.

Could you provide more details on the request send by the browser? And an extract of your directory structure might be helpful as well.

**Comment by jacquesmatthieu** [comment]
sorry dude I was in holidays. So this is my config 
```
app.use('/', expressStaticGzip('../dist-etu-ssr/', {
    enableBrotli: true,
    orderPreference: ['br', 'gzip']
}));
```
files ares build webpack and I 've got gzip file & brotli file in my dist-etu-ssr.

When I do this config .js files are loaded not brotli files or gzip file and I dont know why

**Comment by tkoenig89** [comment]
I'm sorry, but this are not enough information to help, as i pointed out: your setup in general seems okay.

Could you provide a screenshot of the content of `dist-etu-ssr` and one of the browsers network tab showing the requests and response?

**Comment by jacquesmatthieu** [comment]
Hi dude this is my screen shot of my `dist-etu-ssr`
![Capture du 2020-05-04 10-55-21](https://user-images.githubusercontent.com/3845269/80950554-5c67d000-8df6-11ea-8cb2-bdfdb6ea200b.png)

And there is my screen shot of my server (express is loaded in index.js)
![Capture du 2020-05-04 10-55-56](https://user-images.githubusercontent.com/3845269/80950590-6e497300-8df6-11ea-83fb-b0a5ae34a577.png)

**Comment by tkoenig89** [comment]
Hey there,

your directory structure seems to be okay too. I spoted one thing, that could be the issue.
So in your first verbose code example you had this setup:
```JS
server.use('/dist-etu-ssr', expressStaticGzip('../dist-etu-ssr', {
    enableBrotli: true,
    orderPreference: ['br', 'gz']
}));
```
This would only serve files for requests like 'https://\<server\>**/dist-etu-ssr**/main.js' or 'https://\<server\>**/dist-etu-ssr**/CSE.js'. Which seems to me like an odd uri, as I would expect something more like 'https://\<server\>/main.js' or 'https://\<server\>/CSE.js' to be called from browser.

Later you posted this 
```JS
app.use('/', expressStaticGzip('../dist-etu-ssr/', {
    enableBrotli: true,
    orderPreference: ['br', 'gzip']
}));
```
Which should work for the later uris I described above. So maybe you wan't to revisit your current implementation and checkout in detail what kind of requests your browser is doing (screenshots might help, if the above solution does not work).

**Comment by jacquesmatthieu** [comment]
Hi dude,
this is my screenshot of ma response headers
![toto](https://user-images.githubusercontent.com/3845269/81481970-0949af00-9234-11ea-9e5e-b172f30923d3.png)

You have access to my repository (Phoenix), the path of my server is `https://github.com/jacquesmatthieu/phoenix/blob/master/server/index.js`

**Comment by tkoenig89** [comment]
As I did not manage to get all your code running, I reduced your setup to the minimum of `expres-static-gzip`:

```JS
const express = require('express');
const expressStaticGzip = require('express-static-gzip');

const app = express();

app.use('/dist-etu-ssr', expressStaticGzip('../dist-etu-ssr', {
    enableBrotli: true,
    orderPreference: ['br', 'gzip']
}));

const port = 7000;

app.listen(port, () => {
    console.log(`server started at localhost:${port}`);
});
```
This worked without any other change required:
![image](https://user-images.githubusercontent.com/1177652/81496180-fecff980-92b5-11ea-9f21-b98340475600.png)

Concluding there must be an Issue with the rest of your setup. As i did not manage to setup everything and did not have time to realy dive deep I can only suggest, that you reduce your setup one step at a time and test, when express-static-gzip is working. 

At the moment I suspect this line here could somehow shadow `express-static-gzip`:
```JS
app.use('/dist-etu-ssr', serve('../dist-etu-ssr', true));
```
You should not be in need to use `serve-static` in addition to `express-static-gzip`. Just pass your `serve-static` options (see [this](https://github.com/tkoenig89/express-static-gzip#changelog-for-v20)).

**Comment by jacquesmatthieu** [comment]
Hi, 
finally it works. Thanks dude
