### ISSUE TITLE
Expose serveStatic.mime

### ISSUE THREAD

**Issue by Janaka-Steph** [tkoenig89/express-static-gzip#38]
I would like to use serveStatic setHeaders option with a function that checks for mime type, like so: 
`if (serveStatic.mime.lookup(path) === 'text/html') { ... }`
It would be nice to expose `serveStatic` or `mime` so I don't need to install an other npm package.

**Comment by tkoenig89** [comment]
As express-static-gzip is based on serve-static, the later is already
installed, even though it is not listed in your package.json. So there is
no 'additional' package installed, if you add a dependency to serve-static
in your own code.

Stéphane Roche <notifications@github.com> schrieb am Mi., 24. Juni 2020,
22:15:

**Comment by Janaka-Steph** [comment]
Unless it is a different version
