### ISSUE TITLE
'maxAge' does not exist in type 'ExpressStaticGzipOptions'

### ISSUE THREAD

**Issue by Seanmclem** [tkoenig89/express-static-gzip#48]
when using a maxAge option in the object as the second arg to `expressStaticGzip`, I get the TS error `'maxAge' does not exist in type 'ExpressStaticGzipOptions'` which is correct. That type is missing from the options-type. Howver, it's used as an example in the readme ` maxAge: 123,`. Which is correct?

**Comment by Seanmclem** [comment]
nevermind, the readme clearly says the option was moved to serveStatic

**Comment by tkoenig89** [comment]
Thanks for your feedback, and glad you found a solution.

I guess you refer to the part of the readme explaining changes between v1 and v2. I see, that it is the first code example, and you feel tempted to use it like it is. 

```
{
    enableBrotli: true,         // not a serverStatic option, will not be moved
    maxAge: 123,                // not copied, as already present. <-- this
    index: 'main.js',           // copied to serveStatic section
    serveStatic: {
        maxAge: 234,            // will be kept 
        cacheControl: false     // will be kept as well
    }
}
```

Do you think adding something like 'the old way' to the 'wrong' maxAge might help, or should i place the change hint, less prominent?
