### ISSUE TITLE
Browser preferences takes preference over server

### ISSUE THREAD

**Issue by CyberCookie** [tkoenig89/express-static-gzip#50]
Just want to make sure is it correct behavior ?

[sources](https://github.com/tkoenig89/express-static-gzip/blob/master/util/encoding-selection.js#L12)
![image](https://user-images.githubusercontent.com/9907516/166215769-68d6f609-4d7c-436d-9b32-6c0342fe4de9.png)

**Comment by tkoenig89** [comment]
Thanks for pointing this out! This was actually a bug. I thought this has been covered by unit tests, but it seems that was not the case. I added your case as a unit test and fixed the underlying issue. 

The fixed version is already released: 2.1.6.
Let me know when you still have the wrong behavior.

**Comment by CyberCookie** [comment]
Thanks for the reply and for the quick fix!
Everything seems work ok now.
