### ISSUE TITLE
Header "Vary: Accept-Encoding" should be added to all responses which have a precompressed version available

### ISSUE THREAD

**Issue by hannesj** [tkoenig89/express-static-gzip#6]
The Vary header is only used by caching proxies and the failure case can be for example that:

1. user1 fetches app.js without Accept-Encoding header (or with Accept-Encoding value that has no precompressed file such as bzip2)
2. the express-static-gzip does not Vary header in response
3. proxy caches the result
4. user2 asks for the resource with Accept-Encoding: br, gzip
5. the proxy finds the uncompressed version and serves that one (because the response did not have proper Vary)

If the uncompressed also had a Vary header the proxies would not get 'poisoned' with uncompressed versions. This is normally not a problem for internal applications, but with the wild west of internet and it's caches it would be much safer to have the header correctly implemented.

See https://github.com/HSLdevcom/digitransit-ui/pull/1074#discussion_r90913920

**Comment by tkoenig89** [comment]
v0.2.2 has been published to NPM. It contains this latest pull request.

**Comment by hannesj** [comment]
Thanks!
